# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cefe076f5a4f2e80a112c5055dd6b6450454b93bade528707c2fe18edf1105300a342c3e482abb859d69f03f12ba3193d92420aa272c30e04a40ca66e54c197

test:
  secret_key_base: 4a09dea4f778f0a9915f0db50ad88f8bdf8be053042343c288ce123b47ee4bd99b10892e302e1cc2f8afcca76d92a6a17ac065c64ebd9eedd4c3522d9d70aa65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
